version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
      - rust
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      rust-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      rust-major:
        update-types:
          - "major"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: first
      time: "04:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci"
      include: "scope"