[package]
name = "rigwright"
version = "0.1.8"
edition = "2021"
license = "MIT"
authors = ["Rigwright Contributors"]
description = "A radio control HAL and native drivers for amateur-radio applications"
repository = "https://github.com/nicksbar/rigwright"
readme = "README.md"
keywords = ["amateur-radio", "ham-radio", "radio", "icom", "civ"]
categories = ["hardware-support"]
publish = true

[dependencies]
anyhow = "1"
async-trait = "0.1"
serialport = "4"

[dev-dependencies]
futures = "0.3"
